- name: Baixando Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.0-rc.0/node_exporter-1.0.0-rc.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
  tags:
  - install

- name: Criando Diretorio
  file:
    path: /opt/prometheus
    owner: root
    group: root
    mode: '0775'
    state: directory
  tags:
  - install

- name: Desconpactando Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/prometheus/
    remote_src: yes
  tags:
  - install

- name: Copiando Service File
  copy:
    src: node_exporter.conf
    dest: /etc/init/
  tags:
  - install

- name: Criando Link Node Exporter
  file:
    src: /opt/prometheus/node_exporter-1.0.0-rc.0.linux-amd64/node_exporter
    dest: /usr/bin/node_exporter
    owner: root
    group: root
    state: link
  tags:
  - install

- name: Iniciando Servico Node Exporter
  service:
    name: node_exporter
    state: started
  tags:
  - install

- name: Limpando Pacote Node Exporter
  file:
    path: /tmp/node_exporter.tar.gz
    state: absent
  tags:
  - install
