global:
  slack_api_url: '<your_slack_webhook>'

route:
  receiver: 'slack-notifications'
  group_by: [alertname, instance, job, severity]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '<your_channel>'
    text: 'Alert: {{ .GroupLabels.alertname }} | Node: {{ .GroupLabels.instance }} | Group: {{ .GroupLabels.job }} | Severity: {{ .GroupLabels.severity }}'
